import '../JUSTFILE'

ROOT := `cd .. && pwd`

alias i := install

_:
    just --list

[script('bash')]
install:
    deno install --allow-scripts

[script("bash")]
start:
    PORT=3000 deno run -A main.ts

fmt:
    deno fmt
